Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.network "forwarded_port" , guest: 80, host:8080
end
Vagrant.configure("2") do |config|
  config.vm.provision "shell", path: "../startup-script.sh"
end
